apiVersion: v1
kind: Service
metadata:
  name: reto-bancolombia
  labels:
    app: reto-bancolombia
spec:
  type: LoadBalancer
  selector:
    app: reto-bancolombia
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reto-bancolombia
  labels:
    app: reto-bancolombia
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: OctopusExport
  template:
    metadata:
      labels:
        app: reto-bancolombia
        pod: OctopusExport
    spec:
      containers:
        - name: reto-bancolombia
          image: yerson/reto-bancolombia
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
            limits:
              memory: "100Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP